brooklyncentral/advanced-networking

portforwarding/src/main/java/brooklyn/networking/portforwarding/DockerPortForwarder.java
portforwarding/src/main/java/brooklyn/networking/portforwarding/NoopPortForwarder.java
portforwarding/src/main/java/brooklyn/networking/portforwarding/PortForwarderIptables.java
portforwarding/src/main/java/brooklyn/networking/subnet/SubnetTierImpl.java
portforwarding/src/test/java/brooklyn/networking/subnet/SubnetTierTest.java
vcloud-director/src/main/java/brooklyn/networking/vclouddirector/CustomSSLSocketFactory.java
vcloud-director/src/main/java/brooklyn/networking/vclouddirector/FakeSSLSocketFactory.java
vcloud-director/src/main/java/brooklyn/networking/vclouddirector/NatService.java
vcloud-director/src/main/java/brooklyn/networking/vclouddirector/PortForwarderVcloudDirector.java
vcloud-director/src/main/java/brooklyn/networking/vclouddirector/PortForwardingConfig.java
vcloud-director/src/test/java/brooklyn/networking/vclouddirector/NatServiceLiveTest.java

The support in `NatService` for multi-action (i.e. passing in a delta to be applied all at once) is laying the ground work for the approach of having a micro-service that is passes the changes and applies those with appropriate locking (potentially from multiple Brooklyn instances).

Fix nat-service

---

cloudstack/src/main/java/brooklyn/networking/cloudstack/portforwarding/CloudstackPortForwarder.java
common/pom.xml
common/src/main/java/brooklyn/networking/common/subnet/PortForwarder.java
common/src/main/java/brooklyn/networking/common/subnet/PortForwarderAsync.java
common/src/main/java/brooklyn/networking/common/subnet/PortForwarderAsyncImpl.java
common/src/main/java/brooklyn/networking/common/subnet/PortForwarderClient.java
common/src/main/java/brooklyn/networking/subnet/PortForwarder.java
common/src/main/java/brooklyn/networking/subnet/PortForwarderAsync.java
common/src/main/java/brooklyn/networking/subnet/PortForwarderAsyncImpl.java
common/src/main/java/brooklyn/networking/subnet/PortForwarderClient.java
portforwarding/src/main/java/brooklyn/networking/portforwarding/DockerPortForwarder.java
portforwarding/src/main/java/brooklyn/networking/portforwarding/NoopPortForwarder.java
portforwarding/src/main/java/brooklyn/networking/portforwarding/PortForwarderIptables.java
portforwarding/src/main/java/brooklyn/networking/portforwarding/subnet/JcloudsPortforwardingSubnetLocation.java
portforwarding/src/main/java/brooklyn/networking/portforwarding/subnet/JcloudsPortforwardingSubnetMachineLocation.java
portforwarding/src/main/java/brooklyn/networking/subnet/SubnetTier.java
portforwarding/src/main/java/brooklyn/networking/subnet/SubnetTierImpl.java
portforwarding/src/test/java/brooklyn/networking/portforwarding/DockerSubnetTierLiveTest.java
portforwarding/src/test/java/brooklyn/networking/subnet/SubnetTierTest.java
vcloud-director-portforwarding/src/main/java/brooklyn/networking/vclouddirector/PortForwarderVcloudDirector.java

Renames the common module's `brooklyn.networking.subnet` package to `brooklyn.networking.common.subnet`. Doing so prevents both the common and portforwarding modules exporting `brooklyn.networking.subnet`, which would lead to the [split packages](http://wiki.osgi.org/wiki/Split_Packages) problem.
This change will break downstream projects that use `common:brooklyn.networking.subnet`. I can spend more time on this if necessary.

Rename package to avoid OSGi split-package problem

---

vcloud-director-nat-microservice/pom.xml

Avoids the need for a separate `mvn assembly:single` step.

Run assembly plugin automatically during build

---

common/src/main/java/brooklyn/networking/subnet/PortForwarderAsyncImpl.java
common/src/main/java/brooklyn/networking/subnet/PortForwarderClient.java

- The PortForwarderClient package was previously renamed, leaving the old named PortForwarderClient there for backwards compatibility reasons.
- This adds the nested inner classes, which are required for being able to deserialise previously persisted state.
- Does same for PortForwarderAsyncImpl's inner classes

PortForwarderClient: backwards compatibility after names

---

portforwarding/src/main/java/brooklyn/networking/subnet/SubnetEnrichers.java
portforwarding/src/test/java/brooklyn/networking/subnet/SubnetTierTest.java

This ensures that the enricher will publish the transformed port
after the port forwarding rule has been created
Dependant upon https://github.com/apache/incubator-brooklyn/pull/538

Adds AssociationListener to UriTransformingEnricher

---

vcloud-director/src/main/java/brooklyn/networking/vclouddirector/NatService.java
vcloud-director/src/main/java/brooklyn/networking/vclouddirector/NatServiceDispatcher.java
vcloud-director/src/test/java/brooklyn/networking/vclouddirector/AbstractNatServiceLiveTest.java

- Handle concurrent (batched) calls with duplicates in
NatServiceDispatcher.
- Previously was failing because result was different size from input

Nat micro service: handle duplicate targets

---

docs/vCD-nat-microservice.md
vcloud-director-nat-microservice/pom.xml
vcloud-director-nat-microservice/src/main/java/brooklyn/networking/vclouddirector/natservice/api/NatServiceApi.java
vcloud-director-nat-microservice/src/test/java/brooklyn/networking/vclouddirector/natmicroservice/NatServiceMicroserviceAbstractLiveTest.java
vcloud-director-nat-microservice/src/test/java/brooklyn/networking/vclouddirector/natmicroservice/NatServiceMicroserviceTAI2LiveTest.java
vcloud-director-nat-microservice/src/test/java/brooklyn/networking/vclouddirector/natmicroservice/NatServiceMicroserviceTai1LiveTest.java
vcloud-director-nat-microservice/src/test/java/brooklyn/networking/vclouddirector/natmicroservice/NatServiceMicroserviceVcloudAirLiveTest.java
vcloud-director-portforwarding/pom.xml
vcloud-director-portforwarding/src/main/java/brooklyn/networking/vclouddirector/NatDirectClient.java
vcloud-director-portforwarding/src/main/java/brooklyn/networking/vclouddirector/NatMicroserviceClient.java
vcloud-director-portforwarding/src/test/java/brooklyn/networking/vclouddirector/VcloudDirectorSubnetTierLiveTest.java
vcloud-director/pom.xml
vcloud-director/src/main/java/brooklyn/networking/vclouddirector/NatService.java
vcloud-director/src/test/java/brooklyn/networking/vclouddirector/AbstractNatServiceLiveTest.java
vcloud-director/src/test/java/brooklyn/networking/vclouddirector/NatServiceLiveTest.java

add NatServiceMicroserviceTAI2LiveTest
This requires the latest version of cloudsoft/jclouds-vcloud-director to properly test
Also it requires a NAT microservice instance started with something like
`./start.sh  launch --endpointsProperties ~/.brooklyn/dnat-microservice.properties` where the `dnat-microservice.properties` contains the new endpoint for TAI2.0

Fix for TAI2.0 environment

---

vcloud-director-nat-microservice/src/main/java/brooklyn/networking/vclouddirector/natservice/api/NatServiceApi.java
vcloud-director-nat-microservice/src/main/java/brooklyn/networking/vclouddirector/natservice/resources/NatServiceResource.java
vcloud-director-nat-microservice/src/test/java/brooklyn/networking/vclouddirector/natmicroservice/NatServiceMicroserviceAbstractLiveTest.java
vcloud-director/src/main/java/brooklyn/networking/vclouddirector/NatService.java
vcloud-director/src/main/java/brooklyn/networking/vclouddirector/NatServiceDispatcher.java
vcloud-director/src/test/java/brooklyn/networking/vclouddirector/AbstractNatServiceLiveTest.java
vcloud-director/src/test/java/brooklyn/networking/vclouddirector/NatServiceDispatcherLiveTest.java
vcloud-director/src/test/java/brooklyn/networking/vclouddirector/NatServiceDispatcherTest.java

- Allow concurrent operations if acting on different
endpoint or vOrg or vDC
- Pass vDC through REST api (optional parameter)
- Unit test for locking in NatServiceDispatcherTest

NAT microservice: improve locking granularity

---

vcloud-director-nat-microservice/pom.xml

This removes the resteasy dependencies from classpath, which seem to be the culprit for 
`java.lang.AbstractMethodError: javax.ws.rs.core.UriBuilder.uri(Ljava/lang/String;)Ljavax/ws/rs/core/UriBuilder; `

fix classpath issue for NAT micro service

---

vcloud-director-nat-microservice/src/main/java/brooklyn/networking/vclouddirector/natservice/resources/NatServiceResource.java
vcloud-director-portforwarding/src/main/java/brooklyn/networking/vclouddirector/NatDirectClient.java
vcloud-director-portforwarding/src/main/java/brooklyn/networking/vclouddirector/NatMicroserviceClient.java
vcloud-director/src/main/java/brooklyn/networking/vclouddirector/NatService.java
vcloud-director/src/main/java/brooklyn/networking/vclouddirector/NatServiceDispatcher.java
vcloud-director/src/test/java/brooklyn/networking/vclouddirector/AbstractNatServiceLiveTest.java
vcloud-director/src/test/java/brooklyn/networking/vclouddirector/NatServiceLiveTest.java

handle multiple EdgeGateways
If a vOrg has multiple vDC then it will have multiple EdgeGateways. We can’t just get the first, as that might be for the wrong vDC. Therefore find the right one (i.e. the one that has the required public ips).
Also handle there being multiple Gateway Interfaces of type “uplink” in an EdgeGateway - find the one with the public ips, rather than just picking the last one.

Fix: nat microservice multiple vdcs

---

portforwarding/src/main/java/brooklyn/networking/subnet/SubnetTierImpl.java

- open targetPort, rather than node.getLoginPort

Fix SubnetTier’s openPortForwarding

---

common/src/main/java/brooklyn/networking/common/subnet/PortForwarderAsyncImpl.java

- Previously, we’d not open the port on first check because the entity
did not have a machine (though it did have its port attribute set).
We’d only subscribe to attribute-changed for the port, so would
never trigger the check when the machine was finally available.
- Now we also subscribe to LOCATION_ADDED, so it is triggered when
the machine has finished starting up.

Fix for openPortForwarding when attribute already set

---

vcloud-director-nat-microservice/src/test/java/brooklyn/networking/vclouddirector/natmicroservice/NatServiceMicroserviceAbstractLiveTest.java

Make NatServiceMicroserviceAbstractLiveTest fields protected, so usable
by sub-classes

NatServiceMicroserviceAbstractLiveTest fields protected

---

.gitignore
cloudstack/pom.xml
common/pom.xml
pom.xml
portforwarding/pom.xml
scripts/change-version.sh
scripts/release-make.sh
vcloud-director-nat-microservice/pom.xml
vcloud-director-nat-microservice/src/main/assembly/conf/revisions.txt
vcloud-director-portforwarding/pom.xml
vcloud-director/pom.xml

Pulls in changes from https://github.com/brooklyncentral/advanced-networking/pull/65, but using `0.7.0-SNAPSHOT`.

0.7.0 version markers (against 0.7.x branch)

---

vcloud-director/src/main/java/brooklyn/networking/vclouddirector/NatServiceDispatcher.java

- A customer hit an error where their URL used different case from 
that in the microservice’s config file. It therefore did not match
and failed.
- Now do a case-insensitive comparison of the endpoint + vOrg.

NAT microservice config: endpoint case-insensitive

---

cloudstack/src/main/java/brooklyn/networking/cloudstack/legacy/LegacyJcloudsCloudstackSubnetLocation.java
cloudstack/src/main/java/brooklyn/networking/cloudstack/legacy/LegacySubnetTierImpl.java
cloudstack/src/main/java/brooklyn/networking/cloudstack/legacy/VirtualPrivateCloud.java
cloudstack/src/main/java/brooklyn/networking/cloudstack/loadbalancer/CloudStackLoadBalancerImpl.java
common/src/test/java/brooklyn/networking/AttributeMungerTest.java
portforwarding/src/main/java/brooklyn/networking/subnet/SubnetEnrichers.java
portforwarding/src/main/java/brooklyn/networking/subnet/SubnetTierImpl.java
portforwarding/src/test/java/brooklyn/example/ExampleForwardingEntityImpl.java
portforwarding/src/test/java/brooklyn/networking/subnet/SubnetTierTest.java
vcloud-director-nat-microservice/src/test/java/brooklyn/networking/vclouddirector/natmicroservice/NatServiceMicroserviceAbstractLiveTest.java
vcloud-director-portforwarding/src/test/java/brooklyn/networking/vclouddirector/NatMicroserviceClientLiveTest.java
vcloud-director/src/test/java/brooklyn/networking/vclouddirector/AbstractNatServiceLiveTest.java
vcloud-director/src/test/java/brooklyn/networking/vclouddirector/NatServiceLiveTest.java

Pasting code comment here for your convinience when reviewing:
/**
* Transforms a URI (or a HostAndPort) string to the mapped value. Or if there is no
* port-forward rule defined for the given port on this entity's machine, then just 
* return the source value.
* 
* We now handle both URI and HostAndPort to assist backwards compatibility. For example,
* MongoDBServer.MONGO_SERVER_ENDPOINT changed from being a URI to being a ip:port, but
* customers are using the {@link SubnetTier#transformUri(EntityAndAttribute)} to map
* that sensor. When it changed from being a URI, the customer blueprints broke.
*/
The second commit is just updating use of things like `setAttribute()` to `sensors().set()`.

UriTransformingEnricher: handle ip:port as well as URI

---

cloudstack/pom.xml
common/pom.xml
pom.xml
portforwarding/pom.xml
vcloud-director-nat-microservice/pom.xml
vcloud-director-portforwarding/pom.xml
vcloud-director/pom.xml

Was previously 0.8.0-SNAPSHOT, depending on brooklyn 0.8.0-SNAPSHOT

Bump to 0.8.1-SNAPSHOT and depend on Brooklyn 0.8.0-incubating

---

cloudstack/src/test/java/brooklyn/networking/cloudstack/loadbalancer/CloudStackLoadBalancerLiveTest.java

Was causing builds to fail (even though live tests weren’t being run)
because it was instantiating the class and failing to find the war
hello-world.war on the classpath.
Instead lookup the war in the setUp method.

Fix CloudStackLoadBalancerLiveTest

---

vcloud-director/src/main/java/brooklyn/networking/vclouddirector/NatService.java
vcloud-director/src/main/java/brooklyn/networking/vclouddirector/NatServiceDispatcher.java

The main fix is to avoid `NatService` applying empty deltas.
Previously when given an empty delta, it would go through the motions
of applying those (i.e. retrieve the current rules and the apply them).
Now it ensures that is a no-op.

Fix: vCD nat applying empty deltas

---

cloudstack/src/main/java/brooklyn/networking/cloudstack/portforwarding/CloudstackPortForwarder.java

Added a no arg constructor to CloudstackPortForwarder so that it can be used by YAML entities

Added no arg constructor

---

pom.xml

The value for jclouds.groupId will be defined by Brooklyn
via the brooklyn-downstream-parent pom.

Remove jclouds.groupId as it will be obtained from Brooklyn.

---

pom.xml

Note this PR is against 0.10.x. It's a cherry-pick of https://github.com/brooklyncentral/advanced-networking/pull/108, which made the same change in master.

Upgrading to jclouds 1.9.3

---

common/src/test/java/brooklyn/networking/AttributeMungerTest.java
portforwarding/src/test/java/brooklyn/networking/portforwarding/AbstractDockerPortForwarderTest.java
portforwarding/src/test/java/brooklyn/networking/portforwarding/AbstractPortForwarderIptablesTest.java
portforwarding/src/test/java/brooklyn/networking/tunnelling/SshTunnellingIntegrationTest.java

Unit tests updated so that they no longer require the use of `org.apache.brooklyn.core.entity.factory.ApplicationBuilder`
* Where possible unit tests now extend `org.apache.brooklyn.core.test.BrooklynAppUnitTestSupport`
`org.apache.brooklyn.core.entity.factory.ApplicationBuilder` was removed from the brooklyn codebase in https://github.com/apache/brooklyn-server/pull/738

Updates unit tests due to ApplicationBuilder removal
