brooklyncentral/advanced-networking

cloudstack/src/main/java/brooklyn/networking/cloudstack/CloudstackNew40FeaturesClient.java
portforwarding/pom.xml
portforwarding/src/main/java/brooklyn/networking/portforwarding/CloudstackPortForwarder.java

Replaces https://github.com/brooklyncentral/advanced-networking/pull/13/files

added some new functions to the Cloudstack client (strike 2)

---

vcloud-director/src/main/java/brooklyn/networking/vclouddirector/NatService.java

- Only modify the NAT Service, and not all the other services.
Modifying the others (presumably the GatewayIpsecVpnService) can 
cause existing TCP connections to hang because no more packets
will be received!

BROOKLYN-106: fix NAT Service reconfig

---

portforwarding/pom.xml
vcloud-director-nat-microservice/pom.xml
vcloud-director-portforwarding/pom.xml
vcloud-director/pom.xml

Build was failing due to dependencies not found.

Fix dependencies

---

vcloud-director/src/main/java/brooklyn/networking/vclouddirector/NatServiceDispatcher.java

Fix build for Java 6

---

cloudstack/src/main/java/brooklyn/networking/cloudstack/portforwarding/CloudstackPortForwarder.java
common/src/main/java/brooklyn/networking/subnet/PortForwarder.java
common/src/main/java/brooklyn/networking/subnet/PortForwarderClient.java
portforwarding/src/main/java/brooklyn/networking/portforwarding/DockerPortForwarder.java
portforwarding/src/main/java/brooklyn/networking/portforwarding/NoopPortForwarder.java
portforwarding/src/main/java/brooklyn/networking/portforwarding/PortForwarderIptables.java
portforwarding/src/main/java/brooklyn/networking/subnet/SubnetTierImpl.java
portforwarding/src/test/java/brooklyn/networking/subnet/SubnetTierTest.java
vcloud-director-nat-microservice/src/main/java/brooklyn/networking/vclouddirector/natmicroservice/NatMicroServiceMain.java
vcloud-director-portforwarding/src/main/java/brooklyn/networking/vclouddirector/NatDirectClient.java
vcloud-director-portforwarding/src/main/java/brooklyn/networking/vclouddirector/PortForwarderVcloudDirector.java
vcloud-director-portforwarding/src/test/java/brooklyn/networking/vclouddirector/VcloudDirectorSubnetTierLiveTest.java
vcloud-director/src/main/java/brooklyn/networking/vclouddirector/NatService.java

Hooks for calling closePortForwarding (e.g. when VM is being deleted).
Requires https://github.com/apache/incubator-brooklyn/pull/469 to be merged first.

Feature: close port forwarding

---

vcloud-director-nat-microservice/pom.xml
vcloud-director-nat-microservice/src/main/assembly/bin/start.sh
vcloud-director-nat-microservice/src/main/assembly/build-dist.xml

Generates dir, tar.gz and zip, containing jar, dependencies and start.sh.

Create distribution for the VCD NAT-update microservice

---

common/src/main/java/brooklyn/networking/common/subnet/DelegatingPortForwarder.java
common/src/main/java/brooklyn/networking/subnet/PortForwarder.java
common/src/main/java/brooklyn/networking/subnet/PortForwarderAsync.java
common/src/main/java/brooklyn/networking/subnet/PortForwarderAsyncImpl.java
common/src/main/java/brooklyn/networking/subnet/PortForwarderClient.java
portforwarding/src/main/java/brooklyn/networking/subnet/SubnetEnrichers.java
portforwarding/src/main/java/brooklyn/networking/subnet/SubnetTier.java
portforwarding/src/main/java/brooklyn/networking/subnet/SubnetTierImpl.java
portforwarding/src/test/java/brooklyn/networking/subnet/SubnetTierTest.java
vcloud-director-portforwarding/src/test/java/brooklyn/networking/vclouddirector/VcloudDirectorSubnetTierLiveTest.java
vcloud-director-portforwarding/src/test/java/brooklyn/networking/vclouddirector/VcloudDirectorSubnetTierRebindLiveTest.java

Depends on https://github.com/apache/incubator-brooklyn/pull/507

various 20150206

---

portforwarding/src/main/java/brooklyn/networking/subnet/SubnetEnrichers.java
portforwarding/src/test/java/brooklyn/networking/subnet/SubnetTierTest.java

See detailed description under each commit.

Fix: SubnetTier URI transforming enricher with delayed port mapping

---

portforwarding/src/main/java/brooklyn/networking/portforwarding/DockerPortForwarder.java

Updated with Docker API changes in jclouds 1.9.0

Fix for jclouds 1.9.0

---

vcloud-director-nat-microservice/src/main/java/brooklyn/networking/vclouddirector/natmicroservice/NatMicroService.java
vcloud-director-nat-microservice/src/main/java/brooklyn/networking/vclouddirector/natmicroservice/NatMicroServiceMain.java
vcloud-director-portforwarding/src/main/java/brooklyn/networking/vclouddirector/PortForwarderVcloudDirector.java
vcloud-director-portforwarding/src/test/java/brooklyn/networking/vclouddirector/NatMicroserviceClientLiveTest.java
vcloud-director-portforwarding/src/test/java/brooklyn/networking/vclouddirector/VcloudDirectorSubnetTierLiveTest.java
vcloud-director/src/main/java/brooklyn/networking/vclouddirector/NatService.java
vcloud-director/src/main/java/brooklyn/networking/vclouddirector/NatServiceDispatcher.java

@aledsage can you please take a look?

fix VCOMPOSE-1516

---

cloudstack/src/main/java/brooklyn/networking/cloudstack/CloudstackNew40FeaturesClient.java
cloudstack/src/main/java/brooklyn/networking/cloudstack/HttpUtil.java
cloudstack/src/main/java/brooklyn/networking/cloudstack/legacy/LegacyJcloudsCloudstackSubnetLocation.java
cloudstack/src/main/java/brooklyn/networking/cloudstack/portforwarding/CloudstackPortForwarder.java
common/src/main/java/brooklyn/networking/common/subnet/DelegatingPortForwarder.java
common/src/main/java/brooklyn/networking/common/subnet/PortForwarderClient.java
portforwarding/src/main/java/brooklyn/networking/portforwarding/DockerPortForwarder.java
portforwarding/src/main/java/brooklyn/networking/portforwarding/NoopPortForwarder.java
portforwarding/src/main/java/brooklyn/networking/portforwarding/PortForwarderIptables.java
portforwarding/src/main/java/brooklyn/networking/portforwarding/PredefinedPortForwarder.java
portforwarding/src/main/java/brooklyn/networking/portforwarding/subnet/JcloudsPortforwardingSubnetLocation.java
portforwarding/src/main/java/brooklyn/networking/subnet/SubnetTierImpl.java
portforwarding/src/test/java/brooklyn/networking/subnet/SubnetTierTest.java
vcloud-director-portforwarding/src/main/java/brooklyn/networking/vclouddirector/PortForwarderVcloudDirector.java

Updates when building Clocker against Brooklyn 0.9.0-SNAPSHOT, related to the following PRs:
- apache/incubator-brooklyn#1048
- apache/incubator-brooklyn#994
- apache/incubator-brooklyn#1034.
Clocker PR brooklyncentral/clocker#201

Updates to support Clocker with Brooklyn 0.9.0 

---

portforwarding/src/test/java/brooklyn/networking/portforwarding/PredefinedPortForwarderYamlTest.java
vcloud-director-portforwarding/src/test/java/brooklyn/networking/vclouddirector/VcloudDirectorSubnetTierLiveTest.java

- BROOKLYN-182 Update call to findUniqueSshMachineLocation
- Update jclouds-vcloud-director dependency to 1.9.2
@aledsage @andreaturli can you review this

BROOKLYN-182 Update call to findUniqueSshMachineLocation

---

common/pom.xml
common/src/main/java/brooklyn/networking/common/subnet/PortForwarderAsyncImpl.java
common/src/test/java/brooklyn/networking/PortForwarderAsyncTest.java
common/src/test/java/brooklyn/networking/util/TestEntity.java
common/src/test/java/brooklyn/networking/util/TestEntityImpl.java

Ive made a change to JcloudsLocation.releasePortForwarding that makes it asynchronous.
Releates to https://github.com/apache/incubator-brooklyn/pull/1085

Making JcloudsLocation.releasePortForwarding async

---

cloudstack/src/main/java/brooklyn/networking/cloudstack/legacy/LegacyJcloudsCloudstackSubnetLocation.java
portforwarding/src/main/java/brooklyn/networking/portforwarding/subnet/JcloudsPortforwardingSubnetLocation.java

method signature changed for overridden createJcloudsSshMachineLocation

Fix JcloudsPortforwardingSubnetLocation

---

pom.xml

Was previously 1.9.1-20150924.2315

Upgrade: vcloud-director to 1.9.2

---

cloudstack/src/main/java/brooklyn/networking/cloudstack/loadbalancer/CloudStackLoadBalancerImpl.java

Following the changes made in https://github.com/apache/brooklyn-library/pull/10, fixes `CloudStackLoadBalancer`.

Fix CloudStackLoadBalancer

---

portforwarding/src/main/java/brooklyn/networking/subnet/SubnetEnrichers.java

Requires https://github.com/apache/brooklyn-server/pull/191 to first be merged.

Fix subnetEnrichers: allowCyclicPublishing

---

brooklyn-networking-features/pom.xml
pom.xml

Move version props to parent pom

Add parent to brooklyn-networking-features pom

---

cloudstack/src/main/java/brooklyn/networking/cloudstack/legacy/LegacyAbstractSubnetApp.java
cloudstack/src/main/java/brooklyn/networking/cloudstack/legacy/LegacyJcloudsCloudstackSubnetLocation.java
cloudstack/src/main/java/brooklyn/networking/cloudstack/legacy/LegacySubnetTierImpl.java
common/src/test/java/brooklyn/networking/PortForwarderAsyncTest.java
portforwarding/src/main/java/brooklyn/networking/portforwarding/PortForwarderIptables.java
portforwarding/src/main/java/brooklyn/networking/portforwarding/subnet/JcloudsPortforwardingSubnetLocation.java
portforwarding/src/main/java/brooklyn/networking/subnet/SubnetEnrichers.java
portforwarding/src/main/java/brooklyn/networking/subnet/SubnetTierImpl.java
vcloud-director/src/test/java/brooklyn/networking/vclouddirector/NatServiceLiveTest.java

I rebased https://github.com/brooklyncentral/advanced-networking/pull/105 against master, to deal with merge conflicts. And I added `@Override` annotations in a separate commit.

Reflect changes from https://github.com/apache/brooklyn-server/pull/355 (strike 2)

---

cloudstack/src/main/java/brooklyn/networking/cloudstack/CloudStackPrivateNetworkLocationCustomizer.java
cloudstack/src/main/java/brooklyn/networking/cloudstack/legacy/LegacyJcloudsCloudstackSubnetLocation.java
pom.xml
portforwarding/pom.xml

Need to wait for https://github.com/apache/brooklyn-server/pull/481 to be merged first.

Upgrade jclouds 2.0

---

common/pom.xml
common/src/test/java/brooklyn/networking/PortForwarderAsyncTest.java

Change required due to upstream change https://github.com/apache/brooklyn-server/commit/5353ad01ef2972d04a69ff2cd7725280a013be99

Updates mockito import `mockito-all`->`mockito-core`

---

vcloud-director-portforwarding/pom.xml

Unnecessary dependency spotted by @neykov .

Remove unnecessary old airlink dependency

---

portforwarding/src/main/java/brooklyn/networking/portforwarding/subnet/JcloudsPortforwardingSubnetLocation.java

- Raised due to removing of deprecated methods in Brooklyn

Fixing compile error
